const userData = {
  name: "Amit Rajbhandari",
  designation: "FrontEnd Developer",
  avatarUrl: "/avatar.png",
  bannerUrl: "/images/banner-img.png",
  email: "amit.rjbhandari@gmail.com",
  phone: "+977 9802067070",
  address: "Shankhamul, Kathmandu, Nepal",
  about: {},
  totalExperience: 7,
  experience: [
    {
      company: "AMNIL Technologies",
      startDate: "Oct 2015",
      endDate: "Dec 2018",
      title: "Front-end Developer",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a dolor in nunc placerat faucibus id in nibh. Proin tincidunt vel sapien vel ultrices. Cras eu metus et nibh molestie pellentesque at ut nisi. Integer ut nunc sed tellus sodales efficitur. Curabitur varius malesuada convallis. Sed viverra consectetur massa non elementum.",
    },
    {
      company: "Volunteer Website Developer @ 'We' for Change",
      startDate: "Jan 2020",
      endDate: "Mar 2021",
      title: "UI/UX & Front-end Developer",
      desc: "Redesign of 'We' for change organization’s website.",
    },
    {
      company: "Innovation Developer Nepal",
      startDate: "Dec 2018",
      endDate: "Current",
      title: "UI/UX & Front-end Developer",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a dolor in nunc placerat faucibus id in nibh. Proin tincidunt vel sapien vel ultrices. Cras eu metus et nibh molestie pellentesque at ut nisi. Integer ut nunc sed tellus sodales efficitur. Curabitur varius malesuada convallis. Sed viverra consectetur massa non elementum.",
    },
  ],
  project: [
    {
      name: "The Gurkha Spice",
      desc: `Front-End development for The Gurkha Spice in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thegurkhaspice.png",
      tools: ["Wordpress"],
    },
    {
      name: "Kiosk Cloud",
      desc: `Front-End development for Kiosk Cloud in corporation with <a href="https://www.resimator.fi/" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/kioskcloud.png",
      tools: ["JS", "HTML5", "SCSS", "Tailwind"],
    },
    {
      name: "Shangri La Chauffeur",
      desc: `Front-End development for Shangri La Chauffeur Website and CMS in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/shangrila.png",
      tools: ["React", "React Material", "SCSS"],
    },
    {
      name: "DNPWC",
      desc: `Designed DNPWC data entry web platform in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/dnpwc.png",
      tools: ["HTML5", "SCSS"],
    },
    {
      name: "Andelskungen",
      desc: `React Native App design implmentation and development for Andelskungen.`,
      image: "/images/projects/andel.jpg",
      tools: ["React Native", "SCSS"],
    },
    {
      name: "Resimator",
      desc: `Front-End development for Resimator in corporation with <a href="https://www.resimator.fi/" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/resimator.png",
      tools: ["JQuery", "PHP", "HTML5", "SCSS"],
    },
    {
      name: "The Nuts Lounge",
      desc: `Front-End development for The Nuts Lounge in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thenutslounge.png",
      tools: ["Wordpress"],
    },
    {
      name: "Th Learning",
      desc: `Front-End development for Th Learning in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thlearning.png",
      tools: ["Wordpress"],
    },
    {
      name: "We For Change",
      desc: "Front-End development for We For Change",
      image: "/images/projects/weforchange.png",
      tools: ["Wordpress"],
    },
    {
      name: "Hayk",
      desc: `Hybrid Mobile App design implementation and development for Hayk in corporation with <a href="https://www.resimator.fi" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/hayk.jpg",
      tools: ["Ionic", "Angular", "HTML5", "SCSS"],
    },
    {
      name: "BSSTN",
      desc: "Bhaktapur Square Space Time Network's web application to manage internal processes such as billing, client management, subscription packages and statistics.",
      image: "/images/projects/bsstn.jpg",
      tools: ["HTML5", "CSS3"],
    },
    {
      name: "MIDTOWN GALLERIA",
      desc: `Front-End development for MIDTOWN GALLERIA in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/midtown.png",
      tools: ["JQuery", "HTML5", "CSS3"],
    },
    {
      name: "Sanima Bank",
      desc: `Front-End development for Sanima Bank in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/sanimabank.png",
      tools: ["JQuery", "HTML5", "CSS3"],
    },
    {
      name: "SIPRADI Companies",
      desc: `Front-End development for SIPRADI Companies in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/sipradi.png",
      tools: ["JQuery", "HTML5", "CSS3"],
    },
    {
      name: "Prabasi ko Saath",
      desc: `Hybrid Mobile App design implementation and development for Prabasi ko Saath in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/prabasi.jpg",
      tools: ["Ionic", "AngularJS", "HTML5", "SCSS"],
    },
    {
      name: "Nabil Invest App",
      desc: `Hybrid Mobile App design implementation and development for Nabil Invest App in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/nabil.jpg",
      tools: ["Ionic", "AngularJS", "HTML5", "SCSS"],
    },
    {
      name: "Wood Couture",
      desc: `Front-End development for Wood Couture in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/wood-couture.png",
      tools: ["JQuery", "HTML5", "CSS3"],
    },
  ],
  socialLinks: [
    {
      name: "linkedin",
      url: "https://www.linkedin.com/in/amit-rajbhandari-789aab28",
      icon: "/images/social/linkedin.svg",
    },
    {
      name: "facebook",
      url: "https://www.facebook.com/amit.rajBhandari9802",
      icon: "/images/social/facebook.svg",
    },
    {
      name: "instagram",
      url: "https://www.instagram.com/amit_rajbhandari",
      icon: "/images/social/instagram.svg",
    },
    {
      name: "behance",
      url: "https://www.behance.com/",
      icon: "/images/social/behance.svg",
    },
  ],
  tools: [
    { name: "React", image: "/images/social/react.svg" },
    { name: "Next Js", image: "/images/social/nextjs.svg" },
    { name: "Angular", image: "/images/social/angular.svg" },
    { name: "Javascript", image: "/images/social/javascript.svg" },
    { name: "Wordpress", image: "/images/social/wordpress.svg" },
    { name: "Ionic", image: "/images/social/ionic.svg" },
    { name: "Git", image: "/images/social/git.svg" },
    { name: "HTML 5", image: "/images/social/html.svg" },
    { name: "SASS", image: "/images/social/sass.svg" },
    { name: "Git Hub", image: "/images/social/github.svg" },
    { name: "Vscode", image: "/images/social/vscode.svg" },
    { name: "Storybook", image: "/images/social/storybook.svg" },
    { name: "Adobe XD", image: "/images/social/xd.svg" },
    { name: "Adobe Illustrator", image: "/images/social/illustrator.svg" },
    { name: "Adobe Photoshop", image: "/images/social/photoshop.svg" },
    { name: "Figma", image: "/images/social/figma.svg" },
  ],
  resumeUrl: "",
  services: [
    {
      name: "Web Development",
      icon: "/images/icons/icon-web-dev.svg",
      total: 42,
    },
    {
      name: "Mobile App Development",
      icon: "/images/icons/icon-mobile-dev.svg",
      total: 10,
    },
    {
      name: "Web App Development",
      icon: "/images/icons/icon-web-app-dev.svg",
      total: 15,
    },
  ],
};

export default userData;
