const userData = {
  name: "Amit Rajbhandari",
  designation: "FrontEnd Developer",
  avatarUrl: "/avatar.png",
  bannerUrl: "/images/banner-img.png",
  email: "amit.fist@gmail.com",
  phone: "+977 9802067070",
  address: "Shankhamul, Kathmandu, Nepal",
  about: {},
  totalExperience: 7,
  experience: [
    {
      company: "AMNIL Technologies",
      startDate: "Oct 2015",
      endDate: "Dec 2018",
      title: "Front-end Developer",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a dolor in nunc placerat faucibus id in nibh. Proin tincidunt vel sapien vel ultrices. Cras eu metus et nibh molestie pellentesque at ut nisi. Integer ut nunc sed tellus sodales efficitur. Curabitur varius malesuada convallis. Sed viverra consectetur massa non elementum.",
    },
    {
      company: "Innovation Developer Nepal",
      startDate: "Dec 2018",
      endDate: "Current",
      title: "UI/UX & Front-end Developer",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a dolor in nunc placerat faucibus id in nibh. Proin tincidunt vel sapien vel ultrices. Cras eu metus et nibh molestie pellentesque at ut nisi. Integer ut nunc sed tellus sodales efficitur. Curabitur varius malesuada convallis. Sed viverra consectetur massa non elementum.",
    },
  ],
  project: [
    {
      name: "Kiosk Cloud",
      desc: `Front-End development for Kiosk Cloud in corporation with <a href="https://www.resimator.fi/" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/kioskcloud.png",
      tools: ["JS", "HTML", "SCSS", "Tailwind"],
    },
    {
      name: "Shangri La Chauffeur",
      desc: `Front-End development for Shangri La Chauffeur Website and CMS in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/shangrila.png",
      tools: ["React", "React Material", "SCSS"],
    },
    {
      name: "Resimator",
      desc: `Front-End development for Resimator in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/resimator.png",
      tools: ["JQuery", "PHP", "HTML", "SCSS"],
    },
    {
      name: "The Nuts Lounge",
      desc: `Front-End development for The Nuts Lounge in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thenutslounge.png",
      tools: ["Wordpress"],
    },
    {
      name: "Th Learning",
      desc: `Front-End development for Th Learning in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/wood-couture.png",
      tools: ["Wordpress"],
    },
    {
      name: "We For Change",
      desc: "Front-End development for We For Change",
      image: "/images/projects/weforchange.png",
      tools: ["Wordpress"],
    },
    {
      name: "Sanima Bank",
      desc: `Front-End development for Sanima Bank in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/sanimabank.png",
      tools: ["JQuery", "HTML", "CSS"],
    },
    {
      name: "Wood Couture",
      desc: `Front-End development for Wood Couture in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/wood-couture.png",
      tools: ["JQuery", "HTML", "CSS"],
    },
  ],
  socialLinks: [
    {
      name: "facebook",
      url: "https://www.facebook.com/",
      icon: "/images/social/facebook.svg",
    },
    {
      name: "instagram",
      url: "https://www.instagram.com/",
      icon: "/images/social/instagram.svg",
    },
    {
      name: "behance",
      url: "https://www.behance.com/",
      icon: "/images/social/behance.svg",
    },
  ],
  tools: [
    { name: "React", image: "/images/social/react.svg" },
    { name: "Angular", image: "/images/social/angular.svg" },
    { name: "Javascript", image: "/images/social/javascript.svg" },
    { name: "Wordpress", image: "/images/social/wordpress.svg" },
    { name: "Ionic", image: "/images/social/ionic.svg" },
    { name: "Git", image: "/images/social/git.svg" },
    { name: "HTML 5", image: "/images/social/html.svg" },
    { name: "SASS", image: "/images/social/sass.svg" },
    { name: "Git Hub", image: "/images/social/github.svg" },
    { name: "Vscode", image: "/images/social/vscode.svg" },
    { name: "Adobe XD", image: "/images/social/xd.svg" },
    { name: "Adobe Illustrator", image: "/images/social/illustrator.svg" },
    { name: "Adobe Photoshop", image: "/images/social/photoshop.svg" },
    { name: "Figma", image: "/images/social/figma.svg" },
  ],
  resumeUrl: "",
  services: [
    {
      name: "Web Development",
      icon: "/images/icons/icon-web-dev.svg",
      total: 42,
    },
    {
      name: "Mobile App Development",
      icon: "/images/icons/icon-mobile-dev.svg",
      total: 10,
    },
    {
      name: "Web App Development",
      icon: "/images/icons/icon-web-app-dev.svg",
      total: 15,
    },
  ],
};

export default userData;
