const userData = {
  name: "Amit Rajbhandari",
  designation: "FrontEnd Developer",
  avatarUrl: "/avatar.png",
  bannerUrl: "/images/banner-img.png",
  email: "amit.rjbhandari@gmail.com",
  phone: "+977 9802067070",
  address: "Shankhamul, Kathmandu, Nepal",
  about: {},
  totalExperience: 7,
  experience: [
    {
      company: "Resimator Oy",
      startDate: "Dec 2018",
      endDate: "Current",
      title: "UI/UX & Front End Developer",
      desc: "Coming from the field of UI/UX. I started my journey at Resimator as a Front End and UI/UX developer, which was a new opportunity to add another skill to my CV, learned a lot of new frameworks, and worked on various projects and still looking forward to leveling up in future with more skills and projects.",
    },
    {
      company: "'We' for Change",
      startDate: "Jan 2020",
      endDate: "Mar 2021",
      title: "Wordpress Developer(Voluntary)",
      desc: "Starting with the redesign of the organization’s website in WordPress to working with the project Let’s Meditate until the completion of the project it was really professional and fun working with the management team of 'We' For Change.",
    },
    {
      company: "AMNIL Technologies",
      startDate: "Oct 2015",
      endDate: "Dec 2018",
      title: "Sr. Front End Developer",
      desc: "Started my journey as a PHP intern and climbed up to learning HTML, CSS, and Javascript. Worked on numerous projects with different kinds of frameworks like Angular, Svelte, and Ionic. It was a great journey at the company and as a startup of my career I progressed a lot being here.",
    },
  ],
  project: [
    {
      name: "Bridge Inspection Engineers",
      tagline: "WE SPECIALIZE IN STRUCTURE INSPECTION & ASSET MANAGEMENT",
      content: "",
      desc: `Front End development for Bridge Inspection Engineers in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/bridge-inspection.png",
      url: "",
      tools: ["Wordpress"],
      status: "Coming Soon",
    },
    {
      name: "Sierra Homes",
      tagline: "Our Heart Is In Your Home...",
      content:
        "“It All Begins With A Good Foundation”.“Home Is Where Your Heart Is...” From finding the perfect block of land to designing your dream home, the Sierra Homes building process is designed to give you the tools and flexibility to create a home that is an expression of you.",
      desc: `Front End development for Sierra Homes in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/sierra-homes.png",
      url: "",
      tools: ["Wordpress"],
      status: "Coming Soon",
    },
    {
      name: "The Gurkha Spice",
      tagline:
        "Friendly Service, Original Recipes, Perfect location, Fast Pickup",
      content:
        "You can book the restaurant for family dining, birthday parties, private parties, business functions and to organise charity events.",
      desc: `Front End development for The Gurkha Spice in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thegurkhaspice.png",
      url: "https://thegurkhaspice.com.au",
      tools: ["Wordpress"],
      status: "live",
    },
    {
      name: "Kiosk Cloud",
      tagline: "Affordable self-service solution",
      content: "-",
      desc: `Front End development for Kiosk Cloud in corporation with <a href="https://www.resimator.fi/" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/kioskcloud.png",
      url: "https://kioskcloud.io",
      tools: ["JS", "HTML5", "SCSS", "Tailwind"],
      status: "live",
    },
    {
      name: "Shangri La Chauffeur",
      tagline: "Book a ride",
      content:
        "Shangri-La: A remote imaginary place where life approaches perfection. Our ethos behind our service lies in the meaning behind Shangri-La; here we strive for perfection. At Shangri-La, we believe the journey to be as important as the destination and as such ensure your journey is of superlative experience.",
      desc: `Front End development for Shangri La Chauffeur Website and CMS in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/shangrila.png",
      url: "https://shangrilachauffeurs.com.au",
      tools: ["React", "React Material", "SCSS"],
      status: "live",
    },
    {
      name: "DNPWC",
      tagline: "",
      content: "-",
      desc: `Designed DNPWC data entry web platform in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/dnpwc.png",
      url: "",
      tools: ["HTML5", "SCSS"],
      status: "live",
    },
    {
      name: "Andelskungen",
      tagline: "",
      content: "-",
      desc: `React Native App design implmentation and development for Andelskungen.`,
      image: "/images/projects/andel.jpg",
      url: "",
      tools: ["React Native", "SCSS"],
      status: "live",
    },
    {
      name: "Resimator",
      tagline: "TOGETHER, we create SOLUTIONS to accelerate GROWTH",
      content:
        "We believe in disruption and digital innovation of today’s business. We have seen how pandemic like Covid-19 triggered several businesses to adapt to faster digitalisation.",
      desc: `Front End development for Resimator in corporation with <a href="https://www.resimator.fi/" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/resimator.png",
      url: "https://resimator.fi",
      tools: ["JQuery", "PHP", "HTML5", "SCSS"],
      status: "live",
    },
    {
      name: "Karnali Province Sports",
      tagline: "Province Government",
      content:
        "Province Government Ministry of Social Development Karnali Province Sports Development Council",
      desc: `Front End development for Karnali Province Sports`,
      image: "/images/projects/karnali-sports.png",
      url: "https://sports.karnali.gov.np",
      tools: ["JQuery", "PHP", "HTML5", "SCSS"],
      status: "live",
    },
    {
      name: "The Nuts Lounge",
      tagline: "Eat healthy, stay fresh.",
      content:
        "Highest Quality Handmade, 100% Natural, Curated Products, Modern Farm, Alway Fresh, Sustainable.",
      desc: `Front End development for The Nuts Lounge in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thenutslounge.png",
      url: "https://thenutslounge.com.au",
      tools: ["Wordpress"],
      status: "live",
    },
    {
      name: "Th Learning",
      tagline:
        "RESPONSIBLE SERVICE OF ALCOHOL, BASIC FOOD HANDLING, FOOD SAFETY SUPERVISOR, BOOK NOW!",
      content:
        "Training Helps Pty Ltd (ABN 81 152 160 659) is an accredited vocational education and training (VET) college in Australia approved by Australian Skills Quality Authority (ASQA). Australian Skills Quality Authority (ASQA) is a national regulator of VET sector acting as a delegate for Australian Government. as a registered training organisation approved by Australian Skills Quality Authority (ASQA), we meet the required standards for Registered Training Organisations. For you this means that we have been audited to assure that we provide high quality training and have adequate systems, policies and support to meet protect you and meet your learning needs.",
      desc: `Front End development for Th Learning in corporation with <a href="https://www.everestack.com.au/" target="_blank" class="block text-white underline font-medium">Everestack</a>`,
      image: "/images/projects/thlearning.png",
      url: "https://thlearning.edu.au",
      tools: ["Wordpress"],
      status: "live",
    },
    {
      name: "We For Change",
      tagline: "'We' the change makers!",
      content:
        "‘We’ for Change, established in 2012, is a non-profit youth-led organization based in Kathmandu, Nepal. It is the only youth led organization of Nepal that is entirely led by 16 to 24 age group of young people.‘We’ is committed to aware, engage and empower young people of Nepal through leadership and capacity building initiatives. ‘We’ use peer education, sports, meditation, yoga, music and dance to work in the issues of leadership, livelihood, environment sustainability, health, disaster management and civic engagement.",
      desc: "Front End development for We For Change",
      image: "/images/projects/weforchange.png",
      url: "https://www.weforchange.org",
      tools: ["Wordpress"],
      status: "live",
    },
    {
      name: "Hayk",
      tagline: "",
      content: "-",
      desc: `Hybrid Mobile App design implementation and development for Hayk in corporation with <a href="https://www.resimator.fi" target="_blank" class="block text-white underline font-medium">Resimator</a>`,
      image: "/images/projects/hayk.jpg",
      url: "",
      tools: ["Ionic", "Angular", "HTML5", "SCSS"],
      status: "Expired",
    },
    {
      name: "BSSTN",
      tagline: "",
      content:
        "Bhaktapur Square Space Time Network's web application to manage internal processes such as billing, client management, subscription packages and statistics.",
      desc: "Bhaktapur Square Space Time Network's web application to manage internal processes such as billing, client management, subscription packages and statistics.",
      image: "/images/projects/bsstn.jpg",
      url: "-",
      tools: ["HTML5", "CSS3"],
      status: "Expired",
    },
    {
      name: "MIDTOWN GALLERIA",
      tagline: "",
      content:
        "Located in the heart of Pokhara, MidTown Galleria is spread over 50,000 sq. ft., and houses some of the best brands in the country selling gadgets, apparels, shoes, cosmetics, designer wear and so on. Anchored by two state of the art movie theaters, we also have spaces allotted for restaurants, coffee shop, ice cream parlor, ATM lounge and a beauty salon. We are proud to say that we are one of the first (if not the first) differently-abled friendly commercial building in the city.",
      desc: `Front End development for MIDTOWN GALLERIA in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/midtown.png",
      url: "https://www.midtown.com.np/",
      tools: ["JQuery", "HTML5", "CSS3"],
      status: "live",
    },
    {
      name: "SIPRADI Companies",
      tagline: "",
      content:
        "SIPRADI is a major player in AUTOMOTIVE and ALLIED business, one of the largest and most driving brand in Nepal. More than 38 years down the line, SIPRADI has exceeded USD 350 million annual revenue and growing rapidly in automotive, lubricant, financial service and equipment business sectors. It has more than 750 employees and over 650 support staff working to accomplish a shared objective - To deliver quality products and services while adding synergy to the growth of overall brand value.",
      desc: `Front End development for SIPRADI Companies in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/sipradi.png",
      url: "https://www.sipradi.com.np/",
      tools: ["JQuery", "HTML5", "CSS3"],
      status: "live",
    },
    {
      name: "Prabasi ko Saath",
      tagline: "The Mobile App In Nepal designed with and for Migrant Workers.",
      content:
        "The application that helps migrant workers make better decisions through calculating costs and foreign employment income, expenses and savings.",
      desc: `Hybrid Mobile App design implementation and development for Prabasi ko Saath in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/prabasi.jpg",
      url: "http://www.prabasikosath.com/",
      tools: ["Ionic", "AngularJS", "HTML5", "SCSS"],
      status: "live",
    },
    {
      name: "Nabil Invest App",
      tagline: "Finance",
      content:
        "Nabil Invest App is a convenient way to keep track of your investments. Now keep the share market in your pocket. This app gives access to details regarding Nabil Invest DEMAT status, PMS, Today’s Share, Mutual Fund",
      desc: `Hybrid Mobile App design implementation and development for Nabil Invest App in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/nabil.jpg",
      url: "https://play.google.com/store/apps/details?id=com.mobile.nabilinvestmentdemat&hl=en&gl=US",
      tools: ["Ionic", "AngularJS", "HTML5", "SCSS"],
      status: "live",
    },
    {
      name: "Wood Couture",
      tagline: "CUT.CARVE.CREATE",
      content:
        "Every stroke deliberated,each etching calculated. Achieving a fine balance between art and science. Thought goes in to ensure art comes out.",
      desc: `Front End development for Wood Couture in corporation with <a href="https://amniltech.com/" target="_blank" class="block text-white underline font-medium">AMNIL Technologies</a>`,
      image: "/images/projects/wood-couture.png",
      url: "https://www.woodcouture.sg",
      tools: ["JQuery", "HTML5", "CSS3"],
      status: "live",
    },
  ],
  socialLinks: [
    {
      name: "linkedin",
      url: "https://www.linkedin.com/in/amit-rajbhandari-789aab28",
      icon: "/images/social/linkedin.svg",
    },
    {
      name: "facebook",
      url: "https://www.facebook.com/amit.rajBhandari9802",
      icon: "/images/social/facebook.svg",
    },
    {
      name: "instagram",
      url: "https://www.instagram.com/amit_rajbhandari",
      icon: "/images/social/instagram.svg",
    },
    {
      name: "behance",
      url: "https://www.behance.net/amitrb",
      icon: "/images/social/behance.svg",
    },
  ],
  tools: [
    { name: "React", image: "/images/social/react.svg" },
    { name: "Next Js", image: "/images/social/nextjs.svg" },
    { name: "Angular", image: "/images/social/angular.svg" },
    { name: "Javascript", image: "/images/social/javascript.svg" },
    { name: "Wordpress", image: "/images/social/wordpress.svg" },
    { name: "Ionic", image: "/images/social/ionic.svg" },
    { name: "Git", image: "/images/social/git.svg" },
    { name: "HTML 5", image: "/images/social/html.svg" },
    { name: "SASS", image: "/images/social/sass.svg" },
    { name: "Git Hub", image: "/images/social/github.svg" },
    { name: "Vscode", image: "/images/social/vscode.svg" },
    { name: "Storybook", image: "/images/social/storybook.svg" },
    { name: "Adobe XD", image: "/images/social/xd.svg" },
    { name: "Adobe Illustrator", image: "/images/social/illustrator.svg" },
    { name: "Adobe Photoshop", image: "/images/social/photoshop.svg" },
    { name: "Figma", image: "/images/social/figma.svg" },
  ],
  resumeUrl: "",
  services: [
    {
      name: "Website Development",
      icon: "/images/icons/icon-web-dev.svg",
      total: 22,
    },
    {
      name: "Mobile App Development (Hybrid/React Native)",
      icon: "/images/icons/icon-mobile-dev.svg",
      total: 5,
    },
    {
      name: "Web App Development",
      icon: "/images/icons/icon-web-app-dev.svg",
      total: 10,
    },
  ],
};

export default userData;
